//
// SystemVersionResponsePlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemVersionResponsePlatform: Codable, Hashable {

    public var name: String

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
    }
}

