//
// SystemVersionResponseComponents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemVersionResponseComponents: Codable, Hashable {

    /** Name of the component  */
    public var name: String
    /** Version of the component  */
    public var version: String
    /** Key/value pairs of strings with additional information about the component. These values are intended for informational purposes only, and their content is not defined, and not part of the API specification.  These messages can be printed by the client as information to the user.  */
    public var details: [String:String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case version = "Version"
        case details = "Details"
    }
}

