//
// NetworkingConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** NetworkingConfig represents the container&#39;s networking configuration for each of its interfaces. It is used for the networking configs specified in the &#x60;docker create&#x60; and &#x60;docker network connect&#x60; commands.  */
public struct NetworkingConfig: Codable, Hashable {

    /** A mapping of network name to endpoint configuration for that network.  */
    public var endpointsConfig: [String: EndpointSettings]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointsConfig = "EndpointsConfig"
    }
}

