//
// NetworkContainerConnectConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkContainerConnectConfig: Codable, Hashable {

    /** The ID or name of the container to connect to the network. */
    public var container: String? = nil
    public var endpointConfig: EndpointSettings? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
        case endpointConfig = "EndpointConfig"
    }
}

