//
// PortBinding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PortBinding represents a binding between a host IP address and a host port.  */
public struct PortBinding: Codable, Hashable {

    /** Host IP address that the container's port is mapped to. */
    public var hostIp: String? = nil
    /** Host port number that the container's port is mapped to. */
    public var hostPort: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hostIp = "HostIp"
        case hostPort = "HostPort"
    }
}

