//
// PortMap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PortMap describes the mapping of container ports to host ports, using the container&#39;s port-number and protocol as key in the format &#x60;&lt;port&gt;/&lt;protocol&gt;&#x60;, for example, &#x60;80/udp&#x60;.  If a container&#39;s port is mapped for multiple protocols, separate entries are added to the mapping table.  */
public typealias PortMap = [String:[PortBinding]]

