//
// GenericResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** User-defined resources can be either Integer resources (e.g, &#x60;SSD&#x3D;3&#x60;) or String resources (e.g, &#x60;GPU&#x3D;UUID1&#x60;).  */
public struct GenericResource: Codable, Hashable {

    public var namedResourceSpec: GenericResourceNamedResourceSpec? = nil
    public var discreteResourceSpec: GenericResourceDiscreteResourceSpec? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namedResourceSpec = "NamedResourceSpec"
        case discreteResourceSpec = "DiscreteResourceSpec"
    }
}

