//
// GenericResourceNamedResourceSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GenericResourceNamedResourceSpec: Codable, Hashable {

    public var kind: String? = nil
    public var value: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind = "Kind"
        case value = "Value"
    }
}

