//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Address represents an IPv4 or IPv6 IP address. */
public struct Address: Codable, Hashable {

    /** IP address. */
    public var addr: String? = nil
    /** Mask length of the IP address. */
    public var prefixLen: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addr = "Addr"
        case prefixLen = "PrefixLen"
    }
}

