//
// NetworkSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** NetworkSettings exposes the network settings in the API */
public struct NetworkSettings: Codable, Hashable {

    /** Name of the network'a bridge (for example, `docker0`). */
    public var bridge: String? = nil
    /** SandboxID uniquely represents a container's network stack. */
    public var sandboxID: String? = nil
    /** Indicates if hairpin NAT should be enabled on the virtual interface.  */
    public var hairpinMode: Bool? = nil
    /** IPv6 unicast address using the link-local prefix. */
    public var linkLocalIPv6Address: String? = nil
    /** Prefix length of the IPv6 unicast address. */
    public var linkLocalIPv6PrefixLen: Int? = nil
    public var ports: PortMap? = nil
    /** SandboxKey identifies the sandbox */
    public var sandboxKey: String? = nil
    /**  */
    public var secondaryIPAddresses: [Address]? = nil
    /**  */
    public var secondaryIPv6Addresses: [Address]? = nil
    /** EndpointID uniquely represents a service endpoint in a Sandbox.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var endpointID: String? = nil
    /** Gateway address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var gateway: String? = nil
    /** Global IPv6 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var globalIPv6Address: String? = nil
    /** Mask length of the global IPv6 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var globalIPv6PrefixLen: Int? = nil
    /** IPv4 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var iPAddress: String? = nil
    /** Mask length of the IPv4 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var iPPrefixLen: Int? = nil
    /** IPv6 gateway address for this network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var iPv6Gateway: String? = nil
    /** MAC address for the container on the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    public var macAddress: String? = nil
    /** Information about all networks that the container is connected to.  */
    public var networks: [String: EndpointSettings]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bridge = "Bridge"
        case sandboxID = "SandboxID"
        case hairpinMode = "HairpinMode"
        case linkLocalIPv6Address = "LinkLocalIPv6Address"
        case linkLocalIPv6PrefixLen = "LinkLocalIPv6PrefixLen"
        case ports = "Ports"
        case sandboxKey = "SandboxKey"
        case secondaryIPAddresses = "SecondaryIPAddresses"
        case secondaryIPv6Addresses = "SecondaryIPv6Addresses"
        case endpointID = "EndpointID"
        case gateway = "Gateway"
        case globalIPv6Address = "GlobalIPv6Address"
        case globalIPv6PrefixLen = "GlobalIPv6PrefixLen"
        case iPAddress = "IPAddress"
        case iPPrefixLen = "IPPrefixLen"
        case iPv6Gateway = "IPv6Gateway"
        case macAddress = "MacAddress"
        case networks = "Networks"
    }
}

