//
// ContainerChangeResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ContainerChangeResponse = [ContainerChangeResponseItem]

/** change item in response to ContainerChanges operation */
public struct ContainerChangeResponseItem: Codable, Hashable {

    /** Path to file that has changed */
    public var path: String
    /** Kind of change */
    public var kind: Kind

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case kind = "Kind"
    }
    
    public enum Kind: Int, Codable {
        case modified = 0
        case added = 1
        case deleted = 2
    }
}

#if DEBUG
extension ContainerChangeResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ContainerChangeResponse" }
}
#endif
