//
// ContainerUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OK response to ContainerUpdate operation */
public struct ContainerUpdateResponse: Codable, Hashable {

    public var warnings: [String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warnings = "Warnings"
    }
}

