//
// ContainerPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ContainerPruneResponse = [String:ContainerPruneResponseItem]

public struct ContainerPruneResponseItem: Codable, Hashable {

    /** Container IDs that were deleted */
    public var containersDeleted: [String]? = nil
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case containersDeleted = "ContainersDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }
}

#if DEBUG
extension ContainerPruneResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "ContainerPruneResponse" }
}
#endif
