//
// ContainerCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OK response to ContainerCreate operation */
public struct ContainerCreateResponse: Codable, Hashable {

    /** The ID of the created container */
    public var id: String
    /** Warnings encountered when creating the container */
    public var warnings: [String]

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case warnings = "Warnings"
    }
}

#if DEBUG
extension ContainerCreateResponse: FilePreviewable {
    public static var previewFilename: String { "ContainerCreateResponse" }
}
#endif
