//
// DeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A request for devices to be sent to device drivers */
public struct DeviceRequest: Codable, Hashable {

    public var driver: String? = nil
    public var count: Int? = nil
    public var deviceIDs: [String]? = nil
    /** A list of capabilities; an OR list of AND lists of capabilities.  */
    public var capabilities: [[String]]? = nil
    /** Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.  */
    public var options: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case driver = "Driver"
        case count = "Count"
        case deviceIDs = "DeviceIDs"
        case capabilities = "Capabilities"
        case options = "Options"
    }
}

