//
// DeviceMapping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A device mapping between the host and container */
public struct DeviceMapping: Codable, Hashable {

    public var pathOnHost: String? = nil
    public var pathInContainer: String? = nil
    public var cgroupPermissions: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pathOnHost = "PathOnHost"
        case pathInContainer = "PathInContainer"
        case cgroupPermissions = "CgroupPermissions"
    }
}

