//
// HostConfigAllOfLogConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The logging configuration for this container */
public struct HostConfigAllOfLogConfig: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case jsonFile = "json-file"
        case syslog = "syslog"
        case journald = "journald"
        case gelf = "gelf"
        case fluentd = "fluentd"
        case awslogs = "awslogs"
        case splunk = "splunk"
        case etwlogs = "etwlogs"
        case _none = "none"
    }
    public var type: ModelType? = nil
    public var config: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case config = "Config"
    }
}

