//
// ResourcesBlkioWeightDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResourcesBlkioWeightDevice: Codable, Hashable {

    public var path: String? = nil
    public var weight: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case weight = "Weight"
    }
}

