//
// ResourcesUlimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResourcesUlimits: Codable, Hashable {

    /** Name of ulimit */
    public var name: String? = nil
    /** Soft limit */
    public var soft: Int64? = nil
    /** Hard limit */
    public var hard: Int64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case soft = "Soft"
        case hard = "Hard"
    }
}

