//
// ThrottleDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ThrottleDevice: Codable, Hashable {

    /** Device path */
    public var path: String? = nil
    /** Rate */
    public var rate: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case rate = "Rate"
    }
}

