//
// VolumePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias VolumePruneResponse = [String:VolumePruneResponseItem]

public struct VolumePruneResponseItem: Codable, Hashable {

    /** Volumes that were deleted */
    public var volumesDeleted: [String]? = nil
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case volumesDeleted = "VolumesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }
}

#if DEBUG
extension VolumePruneResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "VolumePruneResponse" }
}
#endif
