//
// Volume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Volume: Codable, Hashable {

    public enum Scope: String, Codable, CaseIterable {
        case local = "local"
        case global = "global"
    }
    /** Name of the volume. */
    public var name: String
    /** Name of the volume driver used by the volume. */
    public var driver: String
    /** Mount path of the volume on the host. */
    public var mountpoint: String
    /** Date/Time the volume was created. */
    public var createdAt: String? = nil
    /** Low-level details about the volume, provided by the volume driver. Details are returned as a map with key/value pairs: `{\"key\":\"value\",\"key2\":\"value2\"}`.  The `Status` field is optional, and is omitted if the volume driver does not support this feature.  */
    public var status: [String: [String:String]]? = nil
    /** User-defined key/value metadata. */
    public var labels: [String: String]? = nil
    /** The level at which the volume exists. Either `global` for cluster-wide, or `local` for machine level.  */
    public var scope: Scope = .local
    /** The driver specific options used when creating the volume.  */
    public var options: [String: String]? = nil
    public var usageData: VolumeUsageData? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case driver = "Driver"
        case mountpoint = "Mountpoint"
        case createdAt = "CreatedAt"
        case status = "Status"
        case labels = "Labels"
        case scope = "Scope"
        case options = "Options"
        case usageData = "UsageData"
    }
}

