//
// VolumeListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias VolumeListResponse = [String:VolumeListResponseItem]

/** Volume list response */
public struct VolumeListResponseItem: Codable, Hashable {

    /** List of volumes */
    public var volumes: [VolumeResponse]
    /** Warnings that occurred when fetching the list of volumes.  */
    public var warnings: [String]

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case volumes = "Volumes"
        case warnings = "Warnings"
    }
}

#if DEBUG
extension VolumeListResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "VolumeListResponse" }
}
#endif
