//
// EndpointIPAMConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** EndpointIPAMConfig represents an endpoint&#39;s IPAM configuration.  */
public struct EndpointIPAMConfig: Codable, Hashable {

    public var iPv4Address: String? = nil
    public var iPv6Address: String? = nil
    public var linkLocalIPs: [String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iPv4Address = "IPv4Address"
        case iPv6Address = "IPv6Address"
        case linkLocalIPs = "LinkLocalIPs"
    }
}

