//
// GoPortPort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An open port on a container */
public struct GoPortPort: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case tcp = "tcp"
        case udp = "udp"
        case sctp = "sctp"
    }
    /** Host IP address that the container's port is mapped to */
    public var ip: String? = nil
    /** Port on the container */
    public var privatePort: Int
    /** Port exposed on the host */
    public var publicPort: Int? = nil
    public var type: ModelType

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ip = "IP"
        case privatePort = "PrivatePort"
        case publicPort = "PublicPort"
        case type = "Type"
    }
}

