//
// MountPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A mount point inside a container */
public struct MountPoint: Codable, Hashable {

    public var type: String? = nil
    public var name: String? = nil
    public var source: String? = nil
    public var destination: String? = nil
    public var driver: String? = nil
    public var mode: String? = nil
    public var RW: Bool? = nil
    public var propagation: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case name = "Name"
        case source = "Source"
        case destination = "Destination"
        case driver = "Driver"
        case mode = "Mode"
        case RW
        case propagation = "Propagation"
    }
}

