//
// ContainersIdStatsPidsStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContainersIdStatsPidsStats: Codable, Hashable {

    public var current: Int? = nil
    public var limit: UInt64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case limit
    }
}

