//
// ContainerStatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OK response to ContainerTop operation */
public struct ContainerStatsResponse: Codable, Hashable {

    /** The ID of the container */
    public var id: String? = nil
    /** The Name of the container */
    public var name: String? = nil
    public var read: Date? = nil
    public var numProcs: Int? = nil
    public var preRead: Date? = nil
    public var pidsStats: ContainersIdStatsPidsStats? = nil
    public var blkioStats: BlkioStats? = nil
    public var cpuStats: CPUStats? = nil
    public var preCPUStats: CPUStats? = nil
    public var memoryStats: MemoryStats? = nil
    public var networks: ContainersIdStatsNetworks? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case read
        case numProcs = "num_procs"
        case preRead = "preread"
        case pidsStats = "pids_stats"
        case blkioStats = "blkio_stats"
        case cpuStats = "cpu_stats"
        case preCPUStats = "precpu_stats"
        case memoryStats = "memory_stats"
        case networks = "networks"
    }
}

#if DEBUG
extension ContainerStatsResponse: FilePreviewable {
    public static var previewFilename: String { "ContainerStatsResponse" }
}
extension ContainerStatsResponse: FileStreamPreviewable {
    public static var previewsFilename: String { "ContainerStatsStreamResponse" }
}
#endif
