//
// MemoryStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemoryStats: Codable, Hashable {

    public var usage: Int? = nil
    public var maxUsage: Int? = nil
    public var stats: [String: Int]? = nil
    public var failcnt: Int? = nil
    public var limit: Int? = nil
    public var commit: Int? = nil
    public var commitPeak: Int? = nil
    public var privateWorkingSet: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case usage = "usage"
        case maxUsage = "max_usage"
        case stats = "stats"
        case failcnt = "failcnt"
        case limit = "limit"
        case commit = "commitbytes"
        case commitPeak = "commitpeakbytes"
        case privateWorkingSet = "privateworkingset"
    }
}

