//
// HealthConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A test to perform to check that the container is healthy. */
public struct HealthConfig: Codable, Hashable {

    /** The test to perform. Possible values are:  - `[]` inherit healthcheck from image or parent image - `[\"NONE\"]` disable healthcheck - `[\"CMD\", args...]` exec arguments directly - `[\"CMD-SHELL\", command]` run command with system's default shell  */
    public var test: [String]? = nil
    /** The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    public var interval: Int64? = nil
    /** The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    public var timeout: Int64? = nil
    /** The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.  */
    public var retries: Int? = nil
    /** Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    public var startPeriod: Int64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case test = "Test"
        case interval = "Interval"
        case timeout = "Timeout"
        case retries = "Retries"
        case startPeriod = "StartPeriod"
    }
}

