//
// GraphDriverData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Information about a container&#39;s graph driver. */
public struct GraphDriverData: Codable, Hashable {

    public var name: String
    public var data: [String: String]

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case data = "Data"
    }
}

