//
// ImageRootFS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImageRootFS: Codable, Hashable {

    public var type: String
    public var layers: [String]? = nil
    public var baseLayer: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case layers = "Layers"
        case baseLayer = "BaseLayer"
    }
}

