//
// ImageMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImageMetadata: Codable, Hashable {

    public var lastTagTime: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastTagTime = "LastTagTime"
    }
}

