//
// BuildCache.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BuildCache: Codable, Hashable {

    public var id: String? = nil
    public var parent: String? = nil
    public var type: String? = nil
    public var description: String? = nil
    public var inUse: Bool? = nil
    public var shared: Bool? = nil
    /** Amount of disk space used by the build cache (in bytes).  */
    public var size: Int? = nil
    /** Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    public var createdAt: String? = nil
    /** Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    public var lastUsedAt: String? = nil
    public var usageCount: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "ID"
        case parent = "Parent"
        case type = "Type"
        case description = "Description"
        case inUse = "InUse"
        case shared = "Shared"
        case size = "Size"
        case createdAt = "CreatedAt"
        case lastUsedAt = "LastUsedAt"
        case usageCount = "UsageCount"
    }
}

