//
// MountVolumeOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional configuration for the &#x60;volume&#x60; type. */
public struct MountVolumeOptions: Codable, Hashable {

    /** Populate volume with data from the target. */
    public var noCopy: Bool? = false
    /** User-defined key/value metadata. */
    public var labels: [String: String]? = nil
    public var driverConfig: MountVolumeOptionsDriverConfig? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case noCopy = "NoCopy"
        case labels = "Labels"
        case driverConfig = "DriverConfig"
    }
}

