//
// MountBindOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional configuration for the &#x60;bind&#x60; type. */
public struct MountBindOptions: Codable, Hashable {

    public enum Propagation: String, Codable, CaseIterable {
        case _private = "private"
        case rprivate = "rprivate"
        case shared = "shared"
        case rshared = "rshared"
        case slave = "slave"
        case rslave = "rslave"
    }
    /** A propagation mode with the value `[r]private`, `[r]shared`, or `[r]slave`. */
    public var propagation: Propagation? = nil
    /** Disable recursive bind mount. */
    public var nonRecursive: Bool? = false

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case propagation = "Propagation"
        case nonRecursive = "NonRecursive"
    }
}

