//
// MountTmpfsOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional configuration for the &#x60;tmpfs&#x60; type. */
public struct MountTmpfsOptions: Codable, Hashable {

    /** The size for the tmpfs mount in bytes. */
    public var sizeBytes: Int64? = nil
    /** The permission mode for the tmpfs mount in an integer. */
    public var mode: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sizeBytes = "SizeBytes"
        case mode = "Mode"
    }
}

