//
// MountVolumeOptionsDriverConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Map of driver specific options */
public struct MountVolumeOptionsDriverConfig: Codable, Hashable {

    /** Name of the driver to use to create the volume. */
    public var name: String? = nil
    /** key/value map of driver specific options. */
    public var options: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }
}

