//
// NetworkPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias NetworkPruneResponse = [String:NetworkPruneResponseItem]

public struct NetworkPruneResponseItem: Codable, Hashable {

    /** Networks that were deleted */
    public var networksDeleted: [String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networksDeleted = "NetworksDeleted"
    }
}

#if DEBUG
extension NetworkPruneResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "NetworkPruneResponse" }
}
#endif
