//
// NetworkCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkCreateResponse: Codable, Hashable {

    /** The ID of the created network. */
    public var id: String? = nil
    public var warning: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case warning = "Warning"
    }
}

#if DEBUG
extension NetworkCreateResponse: FilePreviewable {
    public static var previewFilename: String { "NetworkCreateResponse" }
}
#endif
