//
// BlkioStatEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** BlkioStatEntry is one small entity to store a piece of Blkio stats. Not used on Windows.  */
public struct BlkioStatEntry: Codable, Hashable {

    public var major: Int? = nil
    public var minor: Int? = nil
    public var op: String? = nil
    public var value: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case major
        case minor
        case op
        case value
    }
}

