//
// HealthcheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** HealthcheckResult stores information about a single run of a healthcheck probe  */
public struct HealthcheckResult: Codable, Hashable {

    /** Date and time at which this check started in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    public var start: Date? = nil
    /** Date and time at which this check ended in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    public var end: Date? = nil
    /** ExitCode meanings:  - `0` healthy - `1` unhealthy - `2` reserved (considered unhealthy) - other values: error running probe  */
    public var exitCode: Int? = nil
    /** Output from last check */
    public var output: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case start = "Start"
        case end = "End"
        case exitCode = "ExitCode"
        case output = "Output"
    }
}

