//
// Health.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Health stores information about the container&#39;s healthcheck results.  */
public struct Health: Codable, Hashable {

    public var status: HealthStatus? = nil
    /** FailingStreak is the number of consecutive failures */
    public var failingStreak: Int? = nil
    /** Log contains the last few results (oldest first)  */
    public var log: [HealthcheckResult]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status = "Status"
        case failingStreak = "FailingStreak"
        case log = "Log"
    }
}

