//
// ContainerSummaryHostConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContainerSummaryHostConfig: Codable, Hashable {

    public var networkMode: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networkMode = "NetworkMode"
    }
}

