//
// ContainerSummaryResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ContainerSummaryResponse = [String:[ContainerSummaryResponseItem]]

public struct ContainerSummaryResponseItem: Codable, Hashable {

    /** The ID of this container */
    public var id: String? = nil
    /** The names that this container has been given */
    public var names: [String]? = nil
    /** The name of the image used when creating this container */
    public var image: String? = nil
    /** The ID of the image that this container was created from */
    public var imageID: String? = nil
    /** Command to run when starting the container */
    public var command: String? = nil
    /** When the container was created */
    public var created: Int64? = nil
    /** The ports exposed by this container */
    public var ports: [Port]? = nil
    /** The size of files that have been created or changed by this container */
    public var sizeRw: Int64? = nil
    /** The total size of all the files in this container */
    public var sizeRootFs: Int64? = nil
    /** User-defined key/value metadata. */
    public var labels: [String: String]? = nil
    /** The state of this container (e.g. `Exited`) */
    public var state: String? = nil
    /** Additional human-readable status of this container (e.g. `Exit 0`) */
    public var status: String? = nil
    public var hostConfig: ContainerSummaryHostConfig? = nil
    public var networkSettings: ContainerSummaryNetworkSettings? = nil
    public var mounts: [MountPoint]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case names = "Names"
        case image = "Image"
        case imageID = "ImageID"
        case command = "Command"
        case created = "Created"
        case ports = "Ports"
        case sizeRw = "SizeRw"
        case sizeRootFs = "SizeRootFs"
        case labels = "Labels"
        case state = "State"
        case status = "Status"
        case hostConfig = "HostConfig"
        case networkSettings = "NetworkSettings"
        case mounts = "Mounts"
    }
}

#if DEBUG
extension ContainerSummaryResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ContainerListResponse" }
}
#endif
