//
// ContainerSummaryNetworkSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A summary of the container&#39;s network settings */
public struct ContainerSummaryNetworkSettings: Codable, Hashable {

    public var networks: [String: EndpointSettings]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networks = "Networks"
    }
}

