//
// Commit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as &#x60;containerd&#x60;, or &#x60;runC&#x60;.  */
public struct Commit: Codable, Hashable {

    /** Actual commit ID of external tool. */
    public var ID: String? = nil
    /** Commit ID of external tool expected by dockerd as set at build time.  */
    public var expected: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case expected = "Expected"
    }
}

