//
// IndexInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** IndexInfo contains information about a registry. */
public struct IndexInfo: Codable, Hashable {

    /** Name of the registry, such as \"docker.io\".  */
    public var name: String? = nil
    /** List of mirrors, expressed as URIs.  */
    public var mirrors: [String]? = nil
    /** Indicates if the registry is part of the list of insecure registries.  If `false`, the registry is insecure. Insecure registries accept un-encrypted (HTTP) and/or untrusted (HTTPS with certificates from unknown CAs) communication.  > **Warning**: Insecure registries can be useful when running a local > registry. However, because its use creates security vulnerabilities > it should ONLY be enabled for testing purposes. For increased > security, users should add their CA to their system's list of > trusted CAs instead of enabling this option.  */
    public var secure: Bool? = nil
    /** Indicates whether this is an official registry (i.e., Docker Hub / docker.io)  */
    public var official: Bool? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case mirrors = "Mirrors"
        case secure = "Secure"
        case official = "Official"
    }
}

