//
// Runtime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Runtime describes an [OCI compliant](https://github.com/opencontainers/runtime-spec) runtime.  The runtime is invoked by the daemon via the &#x60;containerd&#x60; daemon. OCI runtimes act as an interface to the Linux kernel namespaces, cgroups, and SELinux.  */
public struct Runtime: Codable, Hashable {

    /** Name and, optional, path, of the OCI executable binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  */
    public var path: String? = nil
    /** List of command-line arguments to pass to the runtime when invoked.  */
    public var runtimeArgs: [String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case runtimeArgs
    }
}

