//
// SystemInfoResponseDefaultAddressPools.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemInfoResponseDefaultAddressPools: Codable, Hashable {

    /** The network address in CIDR format */
    public var base: String? = nil
    /** The network pool size */
    public var size: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base = "Base"
        case size = "Size"
    }
}

