//
// SystemInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias SystemInfoResponse = [String:SystemInfoResponseItem]

public struct SystemInfoResponseItem: Codable, Hashable {

    public enum CgroupDriver: String, Codable, CaseIterable {
        case cgroupfs = "cgroupfs"
        case systemd = "systemd"
        case _none = "none"
    }
    public enum CgroupVersion: String, Codable, CaseIterable {
        case _1 = "1"
        case _2 = "2"
    }
    public enum Isolation: String, Codable, CaseIterable {
        case none = ""
        case _default = "default"
        case hyperv = "hyperv"
        case process = "process"
    }
    /** Unique identifier of the daemon.  <p><br /></p>  > **Note**: The format of the ID itself is not part of the API, and > should not be considered stable.  */
    public var id: String? = nil
    /** Total number of containers on the host. */
    public var containers: Int? = nil
    /** Number of containers with status `\"running\"`.  */
    public var containersRunning: Int? = nil
    /** Number of containers with status `\"paused\"`.  */
    public var containersPaused: Int? = nil
    /** Number of containers with status `\"stopped\"`.  */
    public var containersStopped: Int? = nil
    /** Total number of images on the host.  Both _tagged_ and _untagged_ (dangling) images are counted.  */
    public var images: Int? = nil
    /** Name of the storage driver in use. */
    public var driver: String? = nil
    /** Information specific to the storage driver, provided as \"label\" / \"value\" pairs.  This information is provided by the storage driver, and formatted in a way consistent with the output of `docker info` on the command line.  <p><br /></p>  > **Note**: The information returned in this field, including the > formatting of values and labels, should not be considered stable, > and may change without notice.  */
    public var driverStatus: [[String]]? = nil
    /** Root directory of persistent Docker state.  Defaults to `/var/lib/docker` on Linux, and `C:\\ProgramData\\docker` on Windows.  */
    public var dockerRootDir: String? = nil
    public var plugins: PluginsInfo? = nil
    /** Indicates if the host has memory limit support enabled. */
    public var memoryLimit: Bool? = nil
    /** Indicates if the host has memory swap limit support enabled. */
    public var swapLimit: Bool? = nil
    /** Indicates if the host has kernel memory limit support enabled.  <p><br /></p>  > **Deprecated**: This field is deprecated as the kernel 5.4 deprecated > `kmem.limit_in_bytes`.  */
    public var kernelMemory: Bool? = nil
    /** Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.  */
    public var cpuCfsPeriod: Bool? = nil
    /** Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.  */
    public var cpuCfsQuota: Bool? = nil
    /** Indicates if CPU Shares limiting is supported by the host.  */
    public var cpuShares: Bool? = nil
    /** Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.  See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)  */
    public var cpuSet: Bool? = nil
    /** Indicates if the host kernel has PID limit support enabled. */
    public var pidsLimit: Bool? = nil
    /** Indicates if OOM killer disable is supported on the host. */
    public var oomKillDisable: Bool? = nil
    /** Indicates IPv4 forwarding is enabled. */
    public var ipv4Forwarding: Bool? = nil
    /** Indicates if `bridge-nf-call-iptables` is available on the host. */
    public var bridgeNfIptables: Bool? = nil
    /** Indicates if `bridge-nf-call-ip6tables` is available on the host. */
    public var bridgeNfIp6tables: Bool? = nil
    /** Indicates if the daemon is running in debug-mode / with debug-level logging enabled.  */
    public var debug: Bool? = nil
    /** The total number of file Descriptors in use by the daemon process.  This information is only returned if debug-mode is enabled.  */
    public var nfd: Int? = nil
    /** The  number of goroutines that currently exist.  This information is only returned if debug-mode is enabled.  */
    public var numberGoroutines: Int? = nil
    /** Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    public var systemTime: String? = nil
    /** The logging driver to use as a default for new containers.  */
    public var loggingDriver: String? = nil
    /** The driver to use for managing cgroups.  */
    public var cgroupDriver: CgroupDriver? = .cgroupfs
    /** The version of the cgroup.  */
    public var cgroupVersion: CgroupVersion? = ._1
    /** Number of event listeners subscribed. */
    public var numberEventsListener: Int? = nil
    /** Kernel version of the host.  On Linux, this information obtained from `uname`. On Windows this information is queried from the <kbd>HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\</kbd> registry value, for example _\"10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)\"_.  */
    public var kernelVersion: String? = nil
    /** Name of the host's operating system, for example: \"Ubuntu 16.04.2 LTS\" or \"Windows Server 2016 Datacenter\"  */
    public var operatingSystem: String? = nil
    /** Version of the host's operating system  <p><br /></p>  > **Note**: The information returned in this field, including its > very existence, and the formatting of values, should not be considered > stable, and may change without notice.  */
    public var osVersion: String? = nil
    /** Generic type of the operating system of the host, as returned by the Go runtime (`GOOS`).  Currently returned values are \"linux\" and \"windows\". A full list of possible values can be found in the [Go documentation](https://golang.org/doc/install/source#environment).  */
    public var osType: String? = nil
    /** Hardware architecture of the host, as returned by the Go runtime (`GOARCH`).  A full list of possible values can be found in the [Go documentation](https://golang.org/doc/install/source#environment).  */
    public var architecture: String? = nil
    /** The number of logical CPUs usable by the daemon.  The number of available CPUs is checked by querying the operating system when the daemon starts. Changes to operating system CPU allocation after the daemon is started are not reflected.  */
    public var cpuCount: Int? = nil
    /** Total amount of physical memory available on the host, in bytes.  */
    public var memoryTotal: Int64? = nil
    /** Address / URL of the index server that is used for image search, and as a default for user authentication for Docker Hub and Docker Cloud.  */
    public var indexServerAddress: String? = "https://index.docker.io/v1/"
    public var registryConfig: RegistryServiceConfig? = nil
    public var genericResources: [GenericResource]? = nil
    /** HTTP-proxy configured for the daemon. This value is obtained from the [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  */
    public var httpProxy: String? = nil
    /** HTTPS-proxy configured for the daemon. This value is obtained from the [`HTTPS_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  */
    public var httpsProxy: String? = nil
    /** Comma-separated list of domain extensions for which no proxy should be used. This value is obtained from the [`NO_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.  Containers do not automatically inherit this configuration.  */
    public var noProxy: String? = nil
    /** Hostname of the host. */
    public var name: String? = nil
    /** User-defined labels (key/value metadata) as set on the daemon.  <p><br /></p>  > **Note**: When part of a Swarm, nodes can both have _daemon_ labels, > set through the daemon configuration, and _node_ labels, set from a > manager node in the Swarm. Node labels are not included in this > field. Node labels can be retrieved using the `/nodes/(id)` endpoint > on a manager node in the Swarm.  */
    public var labels: [String]? = nil
    /** Indicates if experimental features are enabled on the daemon.  */
    public var experimentalBuild: Bool? = nil
    /** Version string of the daemon.  > **Note**: the [standalone Swarm API](/swarm/swarm-api/) > returns the Swarm version instead of the daemon  version, for example > `swarm/1.2.8`.  */
    public var serverVersion: String? = nil
    /** URL of the distributed storage backend.   The storage backend is used for multihost networking (to store network and endpoint information) and by the node discovery mechanism.  <p><br /></p>  > **Deprecated**: This field is only propagated when using standalone Swarm > mode, and overlay networking using an external k/v store. Overlay > networks with Swarm mode enabled use the built-in raft store, and > this field will be empty.  */
    public var clusterStore: String? = nil
    /** The network endpoint that the Engine advertises for the purpose of node discovery. ClusterAdvertise is a `host:port` combination on which the daemon is reachable by other hosts.  <p><br /></p>  > **Deprecated**: This field is only propagated when using standalone Swarm > mode, and overlay networking using an external k/v store. Overlay > networks with Swarm mode enabled use the built-in raft store, and > this field will be empty.  */
    public var clusterAdvertise: String? = nil
    /** List of [OCI compliant](https://github.com/opencontainers/runtime-spec) runtimes configured on the daemon. Keys hold the \"name\" used to reference the runtime.  The Docker daemon relies on an OCI compliant runtime (invoked via the `containerd` daemon) as its interface to the Linux kernel namespaces, cgroups, and SELinux.  The default runtime is `runc`, and automatically configured. Additional runtimes can be configured by the user and will be listed here.  */
    public var runtimes: [String: Runtime]? = nil
    /** Name of the default OCI runtime that is used when starting containers.  The default can be overridden per-container at create time.  */
    public var defaultRuntime: String? = "runc"
    /** Indicates if live restore is enabled.  If enabled, containers are kept running when the daemon is shutdown or upon daemon start if running containers are detected.  */
    public var liveRestoreEnabled: Bool? = false
    /** Represents the isolation technology to use as a default for containers. The supported values are platform-specific.  If no isolation value is specified on daemon start, on Windows client, the default is `hyperv`, and on Windows server, the default is `process`.  This option is currently not used on other platforms.  */
    public var isolation: Isolation? = ._default
    /** Name and, optional, path of the `docker-init` binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  */
    public var initBinary: String? = nil
    public var containerdCommit: Commit? = nil
    public var runcCommit: Commit? = nil
    public var initCommit: Commit? = nil
    /** List of security features that are enabled on the daemon, such as apparmor, seccomp, SELinux, user-namespaces (userns), and rootless.  Additional configuration options for each security feature may be present, and are included as a comma-separated list of key/value pairs.  */
    public var securityOptions: [String]? = nil
    /** Reports a summary of the product license on the daemon.  If a commercial license has been applied to the daemon, information such as number of nodes, and expiration are included.  */
    public var productLicense: String? = nil
    /** List of custom default address pools for local networks, which can be specified in the daemon.json file or dockerd option.  Example: a Base \"10.10.0.0/16\" with Size 24 will define the set of 256 10.10.[0-255].0/24 address pools.  */
    public var defaultAddressPools: [SystemInfoResponseDefaultAddressPools]? = nil
    /** List of warnings / informational messages about missing features, or issues related to the daemon configuration.  These messages can be printed by the client as information to the user.  */
    public var warnings: [String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "ID"
        case containers = "Containers"
        case containersRunning = "ContainersRunning"
        case containersPaused = "ContainersPaused"
        case containersStopped = "ContainersStopped"
        case images = "Images"
        case driver = "Driver"
        case driverStatus = "DriverStatus"
        case dockerRootDir = "DockerRootDir"
        case plugins = "Plugins"
        case memoryLimit = "MemoryLimit"
        case swapLimit = "SwapLimit"
        case kernelMemory = "KernelMemory"
        case cpuCfsPeriod = "CpuCfsPeriod"
        case cpuCfsQuota = "CpuCfsQuota"
        case cpuShares = "CPUShares"
        case cpuSet = "CPUSet"
        case pidsLimit = "PidsLimit"
        case oomKillDisable = "OomKillDisable"
        case ipv4Forwarding = "IPv4Forwarding"
        case bridgeNfIptables = "BridgeNfIptables"
        case bridgeNfIp6tables = "BridgeNfIp6tables"
        case debug = "Debug"
        case nfd = "NFd"
        case numberGoroutines = "NGoroutines"
        case systemTime = "SystemTime"
        case loggingDriver = "LoggingDriver"
        case cgroupDriver = "CgroupDriver"
        case cgroupVersion = "CgroupVersion"
        case numberEventsListener = "NEventsListener"
        case kernelVersion = "KernelVersion"
        case operatingSystem = "OperatingSystem"
        case osVersion = "OSVersion"
        case osType = "OSType"
        case architecture = "Architecture"
        case cpuCount = "NCPU"
        case memoryTotal = "MemTotal"
        case indexServerAddress = "IndexServerAddress"
        case registryConfig = "RegistryConfig"
        case genericResources = "GenericResources"
        case httpProxy = "HttpProxy"
        case httpsProxy = "HttpsProxy"
        case noProxy = "NoProxy"
        case name = "Name"
        case labels = "Labels"
        case experimentalBuild = "ExperimentalBuild"
        case serverVersion = "ServerVersion"
        case clusterStore = "ClusterStore"
        case clusterAdvertise = "ClusterAdvertise"
        case runtimes = "Runtimes"
        case defaultRuntime = "DefaultRuntime"
        case liveRestoreEnabled = "LiveRestoreEnabled"
        case isolation = "Isolation"
        case initBinary = "InitBinary"
        case containerdCommit = "ContainerdCommit"
        case runcCommit = "RuncCommit"
        case initCommit = "InitCommit"
        case securityOptions = "SecurityOptions"
        case productLicense = "ProductLicense"
        case defaultAddressPools = "DefaultAddressPools"
        case warnings = "Warnings"
    }
}
