//
// LogObjectStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectLogStatus: Codable, Hashable {

    public var container: String? = nil
    public var message: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
        case message = "Message"
    }
}

