//
// LogObjectRegister.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectLogRegister: Codable, Hashable {

    public var container: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
    }
}

