//
// CPUStatsCPUUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CPUStatsCPUUsage: Codable, Hashable {

    public var totalUsage: Int? = nil
    public var percpuUsage: [Int]? = nil
    public var usageInKernelMode: Int? = nil
    public var usageInUserMode: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalUsage = "total_usage"
        case percpuUsage = "percpu_usage"
        case usageInKernelMode = "usage_in_kernelmode"
        case usageInUserMode = "usage_in_usermode"
    }
}

