//
// CPUStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CPUStats: Codable, Hashable {

    public var cpuUsage: CPUStatsCPUUsage? = nil
    public var systemUsage: Int? = nil
    public var onlineCPUs: Int? = nil
    public var throttlingData: CPUStatsThrottlingData? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cpuUsage = "cpu_usage"
        case systemUsage = "system_cpu_usage"
        case onlineCPUs = "online_cpus"
        case throttlingData = "throttling_data"
    }
}

