//
// ContextConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Configuration for a context that is portable between hosts */
public struct ContextConfig: Codable, Hashable {

    /** A description of the context.  */
    public var description: String? = nil
    /** The configuration for the docker endpoint.  */
    public var docker: [String: String]? = nil
    /** Create a context from a named context.  */
    public var from: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description = "Description"
        case docker = "Docker"
        case from = "From"
    }
}

