//
// ContextInspectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContextInspectResponse: Codable, Hashable {

    /** The name of the context */
    public var name: String? = nil
    /** The metadata of the context */
    public var metadata: String? = nil
    /** The endpoint configuration of the context */
    public var endpoints: [String: String]? = nil
    /** The materials for the TLS configuration of the endpoints */
    public var tLSMaterial: [String: [String]]? = nil
    public var storage: ContextInspectResponseStorage? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case metadata = "Metadata"
        case endpoints = "Endpoints"
        case tLSMaterial = "TLSMaterial"
        case storage = "Storage"
    }
}

