//
// EventsActor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventsActor: Codable, Hashable {

    /** The ID of the object emitting the event */
    public var id: String? = nil
    /** Various key/value attributes of the object, depending on its type */
    public var attributes: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "ID"
        case attributes = "Attributes"
    }
}

