//
// SystemEventsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias SystemEventsResponse = [String:SystemEventsResponseItem]

public struct SystemEventsResponseItem: Codable, Hashable {

    /** The type of object emitting the event */
    public var type: String? = nil
    /** The type of event */
    public var action: String? = nil
    public var actor: EventsActor? = nil
    /** Timestamp of event */
    public var time: Int? = nil
    /** Timestamp of event, with nanosecond accuracy */
    public var timeNano: Int64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case action = "Action"
        case actor = "Actor"
        case time
        case timeNano
    }
}

#if DEBUG
extension SystemEventsResponseItem: FileStreamPreviewableAsDict {
    public static var previewFilename: String { "SystemEventsStream" }
}
#endif
