//
// VolumeConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Volume configuration */
public struct VolumeConfig: Codable, Hashable {

    /** The new volume's name. If not specified, Docker generates a name.  */
    public var name: String? = nil
    /** Name of the volume driver to use. */
    public var driver: String? = "local"
    /** A mapping of driver options and values. These options are passed directly to the driver and are driver specific.  */
    public var driverOpts: [String: String]? = nil
    /** User-defined key/value metadata. */
    public var labels: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case driver = "Driver"
        case driverOpts = "DriverOpts"
        case labels = "Labels"
    }
}

