//
// BuildPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias BuildPruneResponse = [String:BuildPruneResponseItem]

public struct BuildPruneResponseItem: Codable, Hashable {

    public var cachesDeleted: [String]? = nil
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cachesDeleted = "CachesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }
}

#if DEBUG
extension BuildPruneResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "BuildPruneResponse" }
}
#endif
