//
// HistoryResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias HistoryResponse = [HistoryResponseItem]

/** individual image layer information in response to ImageHistory operation */
public struct HistoryResponseItem: Codable, Hashable {

    public var id: String
    public var created: Date
    public var createdBy: String
    public var tags: [String]
    public var size: Int64
    public var comment: String

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case created = "Created"
        case createdBy = "CreatedBy"
        case tags = "Tags"
        case size = "Size"
        case comment = "Comment"
    }
}

#if DEBUG
extension HistoryResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ImageHistoryResponse" }
}
#endif
