//
// IdResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response to an API call that returns just an Id */
public struct IdResponse: Codable, Hashable {

    /** The id of the newly created object. */
    public var id: String

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
    }
}

#if DEBUG
extension IdResponse: FilePreviewable {
    public static var previewFilename: String { "ImageIdResponse" }
}
#endif
