//
// ImageSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImageSummary: Codable, Hashable {

    public var id: String
    public var parentId: String
    public var repoTags: [String]
    public var repoDigests: [String]? = nil
    public var created: Date
    public var size: Int64
    public var sharedSize: Int64
    public var virtualSize: Int64
    public var labels: [String: String]? = nil
    public var containers: Int64

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case parentId = "ParentId"
        case repoTags = "RepoTags"
        case repoDigests = "RepoDigests"
        case created = "Created"
        case size = "Size"
        case sharedSize = "SharedSize"
        case virtualSize = "VirtualSize"
        case labels = "Labels"
        case containers = "Containers"
    }
}

#if DEBUG
extension ImageSummary: FilePreviewableAsArray {
    public static var previewFilename: String { "ImageListResponse" }
    
    public static let previews = {
        [String:[ImageSummary]].preview.first!.value
    }()
}
#endif
