//
// ImageDeleteResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ImageDeleteResponse = [ImageDeleteResponseItem]

public struct ImageDeleteResponseItem: Codable, Hashable {

    /** The image ID of an image that was untagged */
    public var untagged: String? = nil
    /** The image ID of an image that was deleted */
    public var deleted: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case untagged = "Untagged"
        case deleted = "Deleted"
    }
}

#if DEBUG
extension ImageDeleteResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ImageDeleteResponse" }
}
#endif
