//
// ImageSearchResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ImageSearchResponse = [ImageSearchResponseItem]

public struct ImageSearchResponseItem: Codable, Hashable {

    public var description: String? = nil
    public var isOfficial: Bool? = nil
    public var isAutomated: Bool? = nil
    public var name: String? = nil
    public var starCount: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case isOfficial = "is_official"
        case isAutomated = "is_automated"
        case name
        case starCount = "star_count"
    }
}

#if DEBUG
extension ImageSearchResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ImageSearchResponse" }
}
#endif
