//
// ImagePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ImagePruneResponse = [String:ImagePruneResponseItem]

public struct ImagePruneResponseItem: Codable, Hashable {

    /** Images that were deleted */
    public var imagesDeleted: [ImageDeleteResponseItem]? = nil
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imagesDeleted = "ImagesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }
}

#if DEBUG
extension ImagePruneResponseItem: FilePreviewableAsDict {
    public static var previewFilename: String { "ImagePruneResponse" }
}
#endif
