//
// IPAMConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IPAMConfig: Codable, Hashable {

    public var subnet: String? = nil
    public var iPRange: String? = nil
    public var gateway: String? = nil
    public var auxAddress: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subnet = "Subnet"
        case iPRange = "IPRange"
        case gateway = "Gateway"
        case auxAddress = "AuxAddress"
    }
}

