//
// IPAM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IPAM: Codable, Hashable {

    /** Name of the IPAM driver to use. */
    public var driver: String? = "default"
    /** List of IPAM configuration options, specified as a map:  ``` {\"Subnet\": <CIDR>, \"IPRange\": <CIDR>, \"Gateway\": <IP address>, \"AuxAddress\": <device_name:IP address>} ```  */
    public var config: [IPAMConfig]? = nil
    /** Driver-specific options, specified as a map. */
    public var options: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case driver = "Driver"
        case config = "Config"
        case options = "Options"
    }
}

