//
// NetworkContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkContainer: Codable, Hashable {

    public var name: String? = nil
    public var endpointID: String? = nil
    public var macAddress: String? = nil
    public var iPv4Address: String? = nil
    public var iPv6Address: String? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case endpointID = "EndpointID"
        case macAddress = "MacAddress"
        case iPv4Address = "IPv4Address"
        case iPv6Address = "IPv6Address"
    }
}

