//
// NetworkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkResponse: Codable, Hashable {

    public var name: String? = nil
    public var id: String? = nil
    public var created: String? = nil
    public var scope: String? = nil
    public var driver: String? = nil
    public var enableIPv6: Bool? = nil
    public var IPAM: IPAM? = nil
    public var _internal: Bool? = nil
    public var attachable: Bool? = nil
    public var ingress: Bool? = nil
    public var containers: [String: NetworkContainer]? = nil
    public var options: [String: String]? = nil
    public var labels: [String: String]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case id = "Id"
        case created = "Created"
        case scope = "Scope"
        case driver = "Driver"
        case enableIPv6 = "EnableIPv6"
        case IPAM
        case _internal = "Internal"
        case attachable = "Attachable"
        case ingress = "Ingress"
        case containers = "Containers"
        case options = "Options"
        case labels = "Labels"
    }
}

#if DEBUG
extension NetworkResponse: FilePreviewable {
    public static var previewFilename: String { "NetworkResponse" }
}
#endif
