//
// ProjectTopResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ProjectTopResponse = [ProjectTopResponseItem]

/** OK response to ProjectTop operation */
public struct ProjectTopResponseItem: Codable, Hashable {

    /** The id */
    public var id: String? = nil
    public var name: String? = nil
    /** The ps column titles */
    public var titles: [String]? = nil
    /** Each process running in the project, where each is process is an array of values corresponding to the titles.  */
    public var processes: [[String]]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "ID"
        case name = "Name"
        case titles = "Titles"
        case processes = "Processes"
    }
}

#if DEBUG
extension ProjectTopResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ProjectTopResponse" }
}
#endif
