//
// ProjectImageResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ProjectImagesResponse = [ProjectImageResponseItem]

public struct ProjectImageResponseItem: Codable, Hashable {

    public var id: String? = nil
    public var containerName: String? = nil
    public var repository: String? = nil
    public var tag: String? = nil
    public var size: Int64? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "ID"
        case containerName = "ContainerName"
        case repository = "Repository"
        case tag = "Tag"
        case size = "Size"
    }
}

#if DEBUG
extension ProjectImageResponseItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ProjectImagesResponse" }
}
#endif
