//
// ProjectContainerSummaryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public typealias ProjectContainerSummary = [ProjectContainerSummaryItem]

public struct ProjectContainerSummaryItem: Codable, Hashable {

    /** The ID of this container */
    public var id: String? = nil
    /** The names that this container has been given */
    public var name: String? = nil
    /** Command to run when starting the container */
    public var command: String? = nil
    public var project: String? = nil
    public var service: String? = nil
    /** The state of this container (e.g. `Exited`) */
    public var state: String? = nil
    public var health: String? = nil
    public var exitCode: Int? = nil
    public var publishers: [PortPublisher]? = nil

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case command = "Command"
        case project = "Project"
        case service = "Service"
        case state = "State"
        case health = "Health"
        case exitCode = "ExitCode"
        case publishers = "Publishers"
    }
}

#if DEBUG
extension ProjectContainerSummaryItem: FilePreviewableAsArray {
    public static var previewFilename: String { "ProjectPsResponse" }
}
#endif
